ccflags-y += -I$(srctree)/techpack/camera-sdm710/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/camera-sdm710/drivers/cam_smmu
ccflags-y += -I$(srctree)/techpack/camera-sdm710/drivers/cam_sync
ccflags-y += -I$(srctree)/techpack/camera-sdm710/drivers/cam_utils

obj-$(CONFIG_SPECTRA_CAMERA) += cam_context.o cam_context_utils.o cam_node.o cam_subdev.o
