ccflags-y += -I$(srctree)/techpack/camera-sdm710/include
ccflags-y += -I$(srctree)/techpack/camera-sdm710/include/uapi
ccflags-y += -I$(srctree)/techpack/camera-sdm710/drivers/cam_sync
ccflags-y += -I$(srctree)/techpack/camera-sdm710/drivers/cam_utils

obj-$(CONFIG_SPECTRA_CAMERA) += cam_sync.o cam_sync_util.o
