ccflags-y += -I$(srctree)/techpack/camera-sdm710/include
ccflags-y += -I$(srctree)/techpack/camera-sdm710/include/uapi
ccflags-y += -I$(srctree)/techpack/camera-sdm710/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/camera-sdm710/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/camera-sdm710/drivers/cam_smmu
ccflags-y += -I$(srctree)/techpack/camera-sdm710/drivers/cam_utils

obj-$(CONFIG_SPECTRA_CAMERA) += cam_soc_util.o cam_io_util.o cam_packet_util.o cam_debug_util.o cam_trace.o cam_common_util.o
