ccflags-y += -I$(srctree)/techpack/camera-sdm710/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/camera-sdm710/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/camera-sdm710/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/camera-sdm710/drivers/cam_cpas

obj-$(CONFIG_SPECTRA_CAMERA) += cam_camsstop_hw.o
